# Site settings
title: Lukasz Wojcik Ruby/Elixir
description: "Blog about Ruby and Elixir development"
url: "https://lukasz-wojcik.github.io/"
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Łukasz Wójcik'
  email: lukasz.wojcik88@wp.pl
  twitter_username: sonar0007
  # facebook_username: sonar0007
  github_username:  lukasz-wojcik
  linkedin_username: "łukasz-wójcik-824803ab"

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
