# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lucas Wojcik Ruby/Elixir
email: lukasz.wojcik88@wp.pl
description: > # this means to ignore newlines until "baseurl:"
  My blog about Ruby and Elixir
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lukasz-wojcik.github.io" # the base hostname & protocol for your site
twitter_username: sonar0007
github_username:  lukasz-wojcik

# Build settings
markdown: kramdown
